### ISSUE TITLE
[Feature request] Offline support.

### ISSUE THREAD

**Issue by nenadalm** [svimanet/blockit#4]
PWA currently doesn't work offline:

![Screenshot_20241114-184529](https://github.com/user-attachments/assets/5a5b559e-8852-4651-a9d2-dffc5a027901)

since it seems it doesn't communicate with any server, it would be nice if it was possible to play offline.

**Comment by svimanet** [comment]
Thanks for the input. I've looked a bit at this, since I was fairly certain I had supported and tested this already. 

After re-testing, I am able to reproduce the issue, only if I have not recently opened the app, and enabled flightmode before I opened it. If I open the app with internet connection, close it, enable flight mode, and re-open the app, it works. Seems to be an issue with the caching policy on the current hosting solution (Github Pages). 

https://github.com/orgs/community/discussions/11884 
Found an open issue about this, where it seems GH pages has a cache-lifetime of 10 minutes, that I will put up as a blocker for this issue.

I currently do not have plans to switch hosting services, since I do not want to maintain a server and/or pay for hosting. Though who know what I feel like doing next year. I've gotten tons of IRL feedback to add a hiscores feature, which would also require some server-validation logic for POSTs.

BUT, this should be fairly easy to host on any server for private caching, since it's just a static website with standard structure. So I encourage you to set up hosting on a private server somewhere, for you and your friends to enjoy better offline support. 

- Bun.sh has a simple http server api builtin: https://bun.sh/docs/api/http

**Comment by nenadalm** [comment]
I think the github pages caches shouldn't be a problem. I have a few of my pwas like backgammon (https://github.com/nenadalm/backgammon/blob/master/resources/private/worker.js) there and I don't experience such issue. I cache every asset in my service worker.

**Comment by nenadalm** [comment]
It looks like caching is not working (tested in Chrome) due to missing files:

![20241115_10h47m23_grim](https://github.com/user-attachments/assets/4a1d86bb-970f-47cd-b5c9-29759f047ea0)

**Comment by svimanet** [comment]
hmm, you might be right. I'll take a closer look after work. On first glance it looks like the the serviceworker script does not use the generated-names for assets. I have another TODO for fixing bundling and deployment, so I might try hitting two birds with one stone

**Comment by svimanet** [comment]
@nenadalm Would you mind retesting? Did some changes, tested ok on my device after ~30m offline

**Comment by nenadalm** [comment]
It seems to be working. Thanks!
